[package]
name = "zk-regex-arkworks"
version = "2.1.0"
license = "MIT"
edition = "2018"
authors = [
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# zk-regex-compiler = { path = "../compiler", default-features = false }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"

ark-ff = "0.3"
ark-r1cs-std = "0.3"
ark-relations = "0.3"
ark-std = "0.3"
ark-bls12-381 = "0.3"
ark-ec = "0.3"
ark-groth16 = "0.3"
rand = "0.8"

[[bin]]
name = "zk-regex-arkworks"
path = "src/bin.rs"
